resolver: lts-13.4

packages:
- haskus-utils/
- haskus-utils-types/
- haskus-utils-data/
- haskus-utils-variant/

extra-deps:
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- focus-1.0.1.3@sha256:adfb0c747394e5dc5d4839167b95f6f9673162b68eb7e7cf11ba39ddf648f8e8

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors

build:
   interleaved-output: true